version: '3'

services:
  postgres:
    image: 'postgres:10.4-alpine'
    environment:
      POSTGRES_DB: 'shopify_base_app_development'
      POSTGRES_USER: 'shopify_base_app_development'
      POSTGRES_PASSWORD: 'yourpassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
  
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    env_file:
      - '.env'

  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    volumes:
      - '.:/app'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis: {}
  postgres: {}
